source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

# ignoring warning from pods
inhibit_all_warnings!

target "PhotoBrowserDemo" do

pod 'SDWebImage'
pod 'DACircularProgress'
pod 'pop'

end
