source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

# ignoring warning from pods
inhibit_all_warnings!

target "PhotoBrowserDemo" do

pod 'DACircularProgress'
pod 'pop'
pod 'SDWebImage'
pod 'VIMediaCache', :git => 'https://github.com/gintechsystems/VIMediaCache.git', :branch => 'develop'

end
